### ISSUE TITLE
All folders empy

### ISSUE THREAD

**Issue by weilbith** [hellricer/cursedtag#3]
I can't see my `.mp3` files when navigating with _cursedtag_. What dependency am I missing to list files? :thinking: 

```sh
$ ls ~/Music/database/ACDC/RockOrBust
ACDC-BaptismByFire.mp3   ACDC-GotSomeRockNRollThunder.mp3 ....
$ cursedtag ~/Music/database/ACDC/RockOrBust
RockOrBust/

```

**Comment by hellricer** [comment]
It's conditioned only by `[[ -x "$(command -v mid3v2)" ]]`. You can try to remove the condition to see if it's caused by that.

Does that also happen on master branch? 
And can you please post version of your bas?

**Comment by weilbith** [comment]
I'm on `master` to be honest. Wanted to test it first without #1.
I replaced this statement which shows me the first file only.
`audio_files+=("$(basename "$(find . -maxdepth 1 -type f -name "*.mp3" -print0)")")`
Anyways I installed this `mutagen` stuff to get `mid3v2`. No I see all files.

**Comment by weilbith** [comment]
Okay

**Comment by weilbith** [comment]
Resize is missing as well. Is this important? Seems to work fine...

**Comment by hellricer** [comment]
Oh, you're right - it seems that `resize` program is actually from `xterm` package, so I need to find other reliable way to get size of terminal.

Will look into it.

**Comment by weilbith** [comment]
Okay, so I guess this is only important when I resize my terminal during working with _cursedtag_?

**Comment by hellricer** [comment]
Exactly.

**Comment by weilbith** [comment]
Could get hard to support all terminal emulators I guess. :thinking: 
But not an issue I expect happen to me. But as input: I'm using Kitty :wink:
